Algoritmo "somaDosQuinhetosPares"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson
// Descrição   : Elaborar um programa que apresente no final o somatório dos valores pares existentes na faixa de
// 1 até 500.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2022
Var
   soma : inteiro
   inicial : inteiro



Inicio
   enquanto (inicial<500) faca
      inicial<-inicial+2
      soma<-soma + inicial
      Escreval(soma)
   fimenquanto


Fimalgoritmo