Algoritmo "somaDosCemPrimeiros"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/09/2022
Var
   soma : inteiro
   inicial : inteiro



Inicio
   enquanto (inicial<100) faca
      inicial<-inicial+1
      soma<-soma + inicial
      Escreval(soma)
   fimenquanto


Fimalgoritmo